#pragma once

#include "Module1_Main/Types.h"

#include <vector>

namespace module3_astar {

/**
 * @brief Position-only 26-neighborhood Jump A* planner.
 *
 * The planner reads only VoxelGrid's raw occupancy. It never queries pose
 * masks, pose tables, swept volumes, or busbar dimensions. The first
 * returned path is the minimum Euclidean-cost path; additional paths are
 * generated by rerunning the search with edges of prior paths excluded.
 */
class JumpAStar {
public:
    static std::vector<std::vector<Point3D>> findPaths(
        const VoxelGrid& map,
        Point3D start,
        Point3D goal,
        int maxPaths);

    static std::vector<Point3D> findPath(
        const VoxelGrid& map,
        Point3D start,
        Point3D goal);
};

} // namespace module3_astar
